# Generated by Django 5.1.4 on 2025-01-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins_epicerie", "0001_initial"),
        ("gestion_epicerie", "0004_remove_avisproduit_id_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id_message", models.AutoField(primary_key=True, serialize=False)),
                ("id_envoyeur", models.IntegerField()),
                ("id_recepteur", models.IntegerField()),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="AvisService",
            fields=[
                (
                    "id_avis_service",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("avis_service", models.TextField()),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "avisservice",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("id_commande", models.AutoField(primary_key=True, serialize=False)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_commande",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("commande_pret", models.CharField(default="NON", max_length=10)),
                ("paye", models.CharField(default="OUI", max_length=5)),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "commande",
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                ("id_message", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "community",
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", models.IntegerField()),
                ("prix_produit", models.DecimalField(decimal_places=0, max_digits=10)),
                ("num_facture", models.CharField(max_length=255)),
                (
                    "id_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_epicerie.commande",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "facture",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id_note", models.AutoField(primary_key=True, serialize=False)),
                ("note", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "note",
            },
        ),
        migrations.CreateModel(
            name="AvisProduit",
            fields=[
                (
                    "id_avis_produit",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("avis_produit", models.TextField()),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
                (
                    "id_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_epicerie.note",
                    ),
                ),
            ],
            options={
                "db_table": "avis_produit",
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", models.IntegerField()),
                (
                    "id_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_epicerie.commande",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.produit",
                    ),
                ),
            ],
            options={
                "db_table": "ligne_commande",
                "unique_together": {("id_commande", "id_produit")},
            },
        ),
        migrations.CreateModel(
            name="Recommandation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "recommandation",
                "unique_together": {("id_produit", "id_utilisateur")},
            },
        ),
    ]
