# Generated by Django 5.1.4 on 2025-01-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id_categorie", models.AutoField(primary_key=True, serialize=False)),
                ("nom_categorie", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "categorie",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id_produit", models.AutoField(primary_key=True, serialize=False)),
                ("nom_produit", models.CharField(max_length=255)),
                ("qte_en_stock", models.IntegerField()),
                ("seuil_min", models.IntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_promotion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "image_produit",
                    models.ImageField(
                        upload_to="admins_epicerie/static/image/photos_produits/"
                    ),
                ),
                ("description", models.TextField()),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("admin", models.CharField(default="OUI", max_length=5)),
                ("auteur", models.CharField(max_length=255)),
                (
                    "id_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins_epicerie.categorie",
                    ),
                ),
            ],
            options={
                "db_table": "produit",
            },
        ),
    ]
