# Generated by Django 5.1.4 on 2024-12-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id_admin", models.AutoField(primary_key=True, serialize=False)),
                ("nom_admin", models.CharField(max_length=255)),
                ("prenom_admin", models.CharField(max_length=255)),
                ("pseudo_admin", models.CharField(max_length=255)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("photo", models.TextField()),
                ("status", models.CharField(max_length=255)),
                ("derniere_date_connexion", models.DateTimeField()),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id_categorie", models.AutoField(primary_key=True, serialize=False)),
                ("nom_categorie", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "categorie",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("id_commande", models.AutoField(primary_key=True, serialize=False)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_commande",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("commande_pret", models.CharField(default="NON", max_length=10)),
                ("paye", models.CharField(default="OUI", max_length=5)),
            ],
            options={
                "db_table": "commande",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("id_utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("pseudo", models.CharField(max_length=255)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("photo", models.CharField(max_length=255)),
                ("status", models.CharField(default="DECONNECTE", max_length=255)),
                ("derniere_connexion", models.DateTimeField(auto_now_add=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id_produit", models.AutoField(primary_key=True, serialize=False)),
                ("nom_produit", models.CharField(max_length=255)),
                ("qte_en_stock", models.IntegerField()),
                ("seuil_min", models.IntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_promotion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image_produit", models.TextField()),
                ("description", models.TextField()),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("admin", models.CharField(default="OUI", max_length=5)),
                ("auteur", models.CharField(max_length=255)),
                (
                    "id_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.categorie",
                    ),
                ),
            ],
            options={
                "db_table": "produit",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id_note", models.AutoField(primary_key=True, serialize=False)),
                ("note", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "note",
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id_message", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "id_envoyeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envoyeur",
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
                (
                    "id_recepteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recepteur",
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", models.IntegerField()),
                ("prix_produit", models.DecimalField(decimal_places=0, max_digits=10)),
                ("num_facture", models.CharField(max_length=255)),
                (
                    "id_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.commande",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "facture",
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                ("id_message", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "community",
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="id_utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_epicerie.utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="AvisService",
            fields=[
                (
                    "id_avis_service",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("avis_service", models.TextField()),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "avisservice",
            },
        ),
        migrations.CreateModel(
            name="AvisProduit",
            fields=[
                (
                    "id_avis_produit",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("avis_produit", models.TextField()),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "id_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.note",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "avis_produit",
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", models.IntegerField()),
                (
                    "id_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.commande",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.produit",
                    ),
                ),
            ],
            options={
                "db_table": "ligne_commande",
                "unique_together": {("id_commande", "id_produit")},
            },
        ),
        migrations.CreateModel(
            name="Recommandation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.produit",
                    ),
                ),
                (
                    "id_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_epicerie.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "recommandation",
                "unique_together": {("id_produit", "id_utilisateur")},
            },
        ),
    ]
