# Generated by Django 5.1.4 on 2024-12-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_epicerie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="image_produit",
            field=models.ImageField(upload_to="images_produits/"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="photo",
            field=models.ImageField(upload_to="photos_utilisateurs/"),
        ),
    ]
