# Generated by Django 5.1.4 on 2024-12-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_epicerie",
            "0002_alter_produit_image_produit_alter_utilisateur_photo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="id_envoyeur",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="messages",
            name="id_recepteur",
            field=models.IntegerField(),
        ),
    ]
